### ISSUE TITLE
Crash if sorting filter under "Add Filter" button

### ISSUE THREAD

**Issue by cachly** [cachly/issues-tracker#1980]
**[Original report](https://bitbucket.org/zedsaidstudio/cachly/issues/1980) by Zed Said Studio LLC (Bitbucket: [zedsaid](https://bitbucket.org/zedsaid), GitHub: [zedsaid](https://github.com/zedsaid)).**

----------------------------------------

**Comment by nnhubbard** [comment]
Hi Cachly/issues-Tracker,

We received your Cachly support request. Someone from our team will get
back to you as soon as possible.

Thank you!

Nic Hubbard
Cachly Creator & Lead Developer
***@***.***
www.cach.ly
<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cach.ly%2F&data=04%7C01%7Cnnhubbard%40puc.edu%7Ca1d6beeef22b4562c12d08d8d6b70a75%7Ca0c272d027684743b621bdb1af3751ef%7C0%7C0%7C637495428943558927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SuNL9x6nbDrpiEc4zY7GsNVAXVyGmAbbTr0VZgtGkzQ%3D&reserved=0>
{#HS:2748692665-2368#}
