### ISSUE TITLE
Pro Offline Maps: Nova Scotia missing county lines

### ISSUE THREAD

**Issue by cachly** [cachly/issues-tracker#4719]
**[Original report](https://bitbucket.org/zedsaidstudio/cachly/issues/4718) by Zed Said Studio LLC (Bitbucket: [zedsaid](https://bitbucket.org/zedsaid), GitHub: [zedsaid](https://github.com/zedsaid)).**

----------------------------------------

**Comment by DNDFireman** [comment]
County line is now working in Nova Scotia. 

Thank you,
