### ISSUE TITLE
Map offset in China

### ISSUE THREAD

**Issue by cachly** [cachly/issues-tracker#5012]
**[Original report](https://bitbucket.org/zedsaidstudio/public-issues-tracker/issues/152) by Thomas Grehl (Bitbucket: [ThomGr](https://bitbucket.org/ThomGr), GitHub: [ThomGr](https://github.com/ThomGr)).**

----------------------------------------

In China the map offset is making Cachly totally useless. Other apps (specifically for the Chinese market, like a metro app for Shanghai) allow to switch the map offset compensation on and off - it depends on the map displayed if the current position is correct or the cache coordinates and WPs. One example of cache owner compensation is GC2VEKQ. Please have a look at https://en.m.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China for some background. 

Would be great to get a fix for that, would even help to boost Geocaching in China. Even the official map has the map display wrong, but in contrast to Cachly the compass is correct. 
Will be in China for two weeks in case you need a beta tester...

**Comment by cachly** [comment]
**Original comment by Zed Said Studio LLC (Bitbucket: [zedsaid](https://bitbucket.org/zedsaid), GitHub: [zedsaid](https://github.com/zedsaid)).**

----------------------------------------

This is an issue that I have had in the back of my mind for a while now. From researching this issue it does not seem like a simple one to solve. iOS does not provide a way to "fix" this issue.

Based on the wiki page you posted I am not sure if it is legal to try and fix this issue as it would be using one of the reverse engineered algorithms posted online.

**Comment by cachly** [comment]
**Original comment by Zed Said Studio LLC (Bitbucket: [zedsaid](https://bitbucket.org/zedsaid), GitHub: [zedsaid](https://github.com/zedsaid)).**

----------------------------------------

"OpenStreetMap, the crowdsourced project to assemble a map of the world, advises that "private surveying and mapping activities are illegal in China".[10]"

**Comment by cachly** [comment]
**Original comment by Thomas Grehl (Bitbucket: [ThomGr](https://bitbucket.org/ThomGr), GitHub: [ThomGr](https://github.com/ThomGr)).**

----------------------------------------

This relates to the creation of map data, not to the use. Apple and others make excellent maps without offset, and e.g. CityMaps2Go compensates the offset als well. The official app has at least the compass right, although the map shows the wrong coordinates - on the map you are 100s of m away, the compass shows 0 m. Even if you do not correct the map display, this would help a lot.

**Comment by cachly** [comment]
**Original comment by Zed Said Studio LLC (Bitbucket: [zedsaid](https://bitbucket.org/zedsaid), GitHub: [zedsaid](https://github.com/zedsaid)).**

----------------------------------------

How are you testing this?

**Comment by cachly** [comment]
**Original comment by Thomas Grehl (Bitbucket: [ThomGr](https://bitbucket.org/ThomGr), GitHub: [ThomGr](https://github.com/ThomGr)).**

----------------------------------------

![1.PNG](https://bitbucket.org/repo/pkzxL5/images/1411749563-1.PNG)I assume you can just simulate a coordinate in China and look at the display of "your" position and the waypoints of any cache where you actually know the location. I will attach some screenshots from Cachly and the official app, with different mas layers each. As said before, the official app gets the compass/distance right. The map display is either correct for the cache or for the current location, depending on the map.
Cachly: OSM offline and online, Apple maps and hybrid. Apple has the current location correct, but not the cache. OSM has the cache location right but not the current location
official app: distance correct, otherwise the same as cachly.
last screenshots: Cachly shows the distance wrong, independent of map layer.

I think most important would be to correct the distance tracking, as this would make cachly a reasonable tool that at least is the same as the official app.

**Comment by cachly** [comment]
**Original comment by Thomas Grehl (Bitbucket: [ThomGr](https://bitbucket.org/ThomGr), GitHub: [ThomGr](https://github.com/ThomGr)).**

----------------------------------------

**Comment by cachly** [comment]
I do not know if this is still an issue. Need to investigate.

**Comment by ThomGr** [comment]
I am sure it is, but haven’t checked since 18 monthsAm 30.10.2024 um 19:32 schrieb Nicholas Hubbard ***@***.***>:﻿
I do not know if this is still an issue. Need to investigate.
