### ISSUE TITLE
Allow switching between localized and english version

### ISSUE THREAD

**Issue by cachly** [cachly/issues-tracker#5022]
**[Original report](https://bitbucket.org/zedsaidstudio/public-issues-tracker/issues/162) by Thomas Grehl (Bitbucket: [ThomGr](https://bitbucket.org/ThomGr), GitHub: [ThomGr](https://github.com/ThomGr)).**

----------------------------------------

1. This would make it easier for translators to check that the original strings were correctly localized. Also, this makes it easier to find the original string in the xliff file.

2. Some users might like the english version more than the localized one, as Geocaching is a game that is full of english terms even used in foreign languages. I have e.g. chose to use geocaching.com in the english version to avoid weird localisation (back in 2010, now it is too late to change ;-) although the localization for German in probalbly excellent).

**Comment by cachly** [comment]
iOS provides this.

**Comment by nnhubbard** [comment]
Hi Cachly/issues-Tracker,

We received your Cachly support request. Someone from our team will get
back to you as soon as possible.

Thank you!

Nic Hubbard
Cachly Creator & Lead Developer
***@***.***
www.cach.ly
<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cach.ly%2F&data=04%7C01%7Cnnhubbard%40puc.edu%7Ca1d6beeef22b4562c12d08d8d6b70a75%7Ca0c272d027684743b621bdb1af3751ef%7C0%7C0%7C637495428943558927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SuNL9x6nbDrpiEc4zY7GsNVAXVyGmAbbTr0VZgtGkzQ%3D&reserved=0>
{#HS:2748713020-2370#}

**Comment by nnhubbard** [comment]
Hi Cachly/issues-Tracker,

We received your Cachly support request. Someone from our team will get
back to you as soon as possible.

Thank you!

Nic Hubbard
Cachly Creator & Lead Developer
***@***.***
www.cach.ly
<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cach.ly%2F&data=04%7C01%7Cnnhubbard%40puc.edu%7Ca1d6beeef22b4562c12d08d8d6b70a75%7Ca0c272d027684743b621bdb1af3751ef%7C0%7C0%7C637495428943558927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SuNL9x6nbDrpiEc4zY7GsNVAXVyGmAbbTr0VZgtGkzQ%3D&reserved=0>
{#HS:2748713016-2369#}
