### ISSUE TITLE
Mix of Japan/Chinese on New Japan map

### ISSUE THREAD

**Issue by Nobby147** [cachly/issues-tracker#5058]
When zoomed out, the display is correctly in Japanese, but when zoomed in, characters that appear to be Chinese are displayed on top of the Japanese. When zoomed in further, there is no Japanese, only Chinese.

**Comment by cachly** [comment]
Hi Cachly/issues-Tracker,

We received your Cachly support request. Someone from our team will get
back to you as soon as possible.

Thank you!

Nic Hubbard
Cachly Creator & Lead Developer
***@***.***
www.cach.ly
<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cach.ly%2F&data=04%7C01%7Cnnhubbard%40puc.edu%7Ca1d6beeef22b4562c12d08d8d6b70a75%7Ca0c272d027684743b621bdb1af3751ef%7C0%7C0%7C637495428943558927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SuNL9x6nbDrpiEc4zY7GsNVAXVyGmAbbTr0VZgtGkzQ%3D&reserved=0>
{#HS:2748605701-2361#}

**Comment by Nobby147** [comment]
It is complicated, but the Chinese characters on the map are Japanese, and the alphabets above them are seems![image](https://github.com/user-attachments/assets/e96b1cae-d20e-4dec-9061-eb6aabb0fc48) to be Chinese.

**Comment by cachly** [comment]
@Nobby147 Could you mark on the screenshot which text is Japanese and which is Chinese?

**Comment by cachly** [comment]
Hi Cachly/issues-Tracker,

We received your Cachly support request. Someone from our team will get
back to you as soon as possible.

Thank you!

Nic Hubbard
Cachly Creator & Lead Developer
***@***.***
www.cach.ly
<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cach.ly%2F&data=04%7C01%7Cnnhubbard%40puc.edu%7Ca1d6beeef22b4562c12d08d8d6b70a75%7Ca0c272d027684743b621bdb1af3751ef%7C0%7C0%7C637495428943558927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SuNL9x6nbDrpiEc4zY7GsNVAXVyGmAbbTr0VZgtGkzQ%3D&reserved=0>
{#HS:2748613432-2362#}

**Comment by Nobby147** [comment]
Red squares: Japanese
Blue squares: Chinese?

Further，name of low mountains are only shown in Chinese.

![map1](https://github.com/user-attachments/assets/5054f7ea-2736-4625-9255-698e88f759ee)
![map2](https://github.com/user-attachments/assets/bb800c89-480b-4d3e-ba3e-45fd8410b63c)

**Comment by cachly** [comment]
And was the old map correct?

**Comment by ThomGr** [comment]
Yes, the POI is missing for all the local university buildings. Am 30.10.2024 um 06:19 schrieb Nicholas Hubbard ***@***.***>:﻿
And was the old map correct?

**Comment by Nobby147** [comment]
Confirmed the old map was correct.

**Comment by cachly** [comment]
Thanks. What are the coordinates for the location in the screenshots?

**Comment by Nobby147** [comment]
The coords of the first shot:
N 035° 30.450' E 139° 33.299'

As for the second, I don’t remember as I chose randomly. So here is the another example of low mountain. 
N 036° 18.460' E 140° 08.536'

**Comment by Nobby147** [comment]
I said low mountains but found interesting mountains. 

In the new map, the name of 1223m high mountain is English but it's fine. The one of 1218m mountain is in Chinese and it's unacceptable because Japanese don't understand. 

The first screenshot is old map and second new map. In old map, they are in English and Japanese respectively. 

![image](https://github.com/user-attachments/assets/2923bfc9-e5e7-4b9d-812a-370ef1bc28c7)
![image](https://github.com/user-attachments/assets/1fcba6da-173a-4e12-86dd-9a8c5796b2de)

**Comment by cachly** [comment]
Thanks for the detailed info and screenshots. I have a fix coming in the next beta that I will have you test.

**Comment by cachly** [comment]
Fixed in 8.0.7 (4)
