### ISSUE TITLE
The Find Count filter should default to Greater Than or Equal To

### ISSUE THREAD

**Issue by Mr-Gigabyte** [cachly/issues-tracker#5059]
The default setting for the Favorite Count filter is "is greater than or equal to," which makes sense. Similarly, the Favorite Percentage filter also defaults to "is greater than or equal to," which is logical as well. 

However, the Find Count filter defaults to "less than." I suggest that it should be changed to "greater than or equal to." I use two variations of this filter on every offline list to identify popular caches. In the hundreds of times I've used this filter, I've only changed it to a different operator once, and that was to find caches with no finds. 

I recommend setting the default for the Find Count filter to "greater than or equal to," consistent with the other similar filters.

**Comment by cachly** [comment]
Hi Cachly/issues-Tracker,

We received your Cachly support request. Someone from our team will get
back to you as soon as possible.

Thank you!

Nic Hubbard
Cachly Creator & Lead Developer
***@***.***
www.cach.ly
<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cach.ly%2F&data=04%7C01%7Cnnhubbard%40puc.edu%7Ca1d6beeef22b4562c12d08d8d6b70a75%7Ca0c272d027684743b621bdb1af3751ef%7C0%7C0%7C637495428943558927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SuNL9x6nbDrpiEc4zY7GsNVAXVyGmAbbTr0VZgtGkzQ%3D&reserved=0>
{#HS:2748629358-2363#}
