### ISSUE TITLE
New offline maps don’t show university POI

### ISSUE THREAD

**Issue by ThomGr** [cachly/issues-tracker#5060]
See screenshots
![IMG_3615](https://github.com/user-attachments/assets/57c9f23b-ccf2-474c-9628-04a25cf36c86)
![IMG_3614](https://github.com/user-attachments/assets/3116cf5b-082e-4a1f-8806-2f52aad77818)

**Comment by ThomGr** [comment]
Also other POI icons (ATM, some business) missing, while the same don't show at all (no label or icon) in the old maps. 

![image](https://github.com/user-attachments/assets/709a91d5-58fd-4187-9953-611b895beaae)

**Comment by ThomGr** [comment]
N 052° 07.875' E 007° 41.636'

**Comment by cachly** [comment]
Fixed in 8.0.7 (4).
