### ISSUE TITLE
'Export GPX': add default name for 'Export Title' and make behaviour consistent

### ISSUE THREAD

**Issue by MichaelHobi** [cachly/issues-tracker#5063]
Some small inconsistency, that maybe could be easily corrected: When in the list of offline lists and clicking on '...' and 'Export GPX' the name of the GPX defaults to the name of the offline list. When an offline list is selected and the '...' in the upper right (e.g. in map view) is clicked and then 'Export GPX', the 'Export Title' is empty. Would be good to also have a default name for the 'Export Title' the same as the offline list and to make the behaviour consistent.

**Comment by cachly** [comment]
Fixed in 8.0.7 (5)

**Comment by MichaelHobi** [comment]
Works, thank you
