### ISSUE TITLE
Pro Offline Maps: County label differences

### ISSUE THREAD

**Issue by GeekNJ** [cachly/issues-tracker#5066]
While testing new offline maps, I noticed a difference in the county label text style. Current maps show consistent county labels while new maps show varied county name style.  Location: N 026° 11.683' W 080° 50.680'

Newer map with inconsistent county name styles:
![County_Map_Style_new](https://github.com/user-attachments/assets/8c8c5eb4-5024-4e3b-ad36-3e836e197a9f)

Currently released map with consistent county name styles:
![County_Map_Style_cuurent](https://github.com/user-attachments/assets/f4c27591-c99b-4467-8a32-3fd57d659104)

**Comment by cachly** [comment]
Fixed in 8.0.7 (5)
