### ISSUE TITLE
Pro Offline Maps - Trail distance differences

### ISSUE THREAD

**Issue by GeekNJ** [cachly/issues-tracker#5067]
Seeing differences on the distances displayed for trails. I'm swapping between the current and new maps without moving and the differences displayed are very different. Location in NJ: N 040° 51.423' W 073° 57.513'

Current map:
![trail_distance_current](https://github.com/user-attachments/assets/794721c9-0b8f-4c99-82cc-2a1eefffdd3a)

New map:
![trail_distance_new](https://github.com/user-attachments/assets/9e7d815f-e717-44bd-9ee2-983243ed4f2e)

**Comment by cachly** [comment]
Fixed in regenerated maps.
