### ISSUE TITLE
Pin drag failing in Google Maps

### ISSUE THREAD

**Issue by rragan** [cachly/issues-tracker#5071]
**Describe the bug**
I can long press and drop a pin in Apple Maps and in off-line maps and then drag the pin to a more precise location. In Google Maps and satellite view this only results in creating more pins as I press to try to drag. 

**To Reproduce**
1. Drop a pin in Google maps view.
2. Press on the pin to drag it to a slightly different location.
3. Notice that instead, a new pin is created.

** Expected Behavior **
Like what happens in Apple Maps and off-line maps, dragging the pin to a new location works

**Screenshots**

**Cachly version**
 - Latest beta

**iOS device (please complete the following information):**
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 18.0]

**Additional context**

**Comment by cachly** [comment]
Fixed in 8.0.7 (5)
