### ISSUE TITLE
DNFs not showing up consistently on the map.

### ISSUE THREAD

**Issue by BenjiG59** [cachly/issues-tracker#5094]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Cachly version**
 - Version: [e.g. 8.0.6 (1)]

**iOS device (please complete the following information):**
 - Device: [e.g. iPhone 14]
 - OS: [e.g. iOS 13.1]

**Additional context**

**Comment by cachly** [comment]
Fixed in build 9.
