### ISSUE TITLE
Delorme related crash

### ISSUE THREAD

**Issue by rragan** [cachly/issues-tracker#5096]
**Describe the bug**
Opened California Delorme-> View All -> drill into a page then close and Cachly quits

**To Reproduce**
See above

**Expected behavior**
Not crash 

**Screenshots**

**Cachly version**
 - Beta Version: [8.0.7 (8)]

**iOS device (please complete the following information):**
 - Device: iphone 16
 - OS: 18.1

**Additional context**
I had crash after crash and then went to write this up. Now when I go back it doesn't crash. Maybe the dump I sent will offer insight.

**Comment by cachly** [comment]
This crash is specific to Google Maps and will be fixed for the next beta.
