### ISSUE TITLE
DeLorme has wrong count of found pages

### ISSUE THREAD

**Issue by ThomGr** [cachly/issues-tracker#5097]
**Describe the bug**
While counties seems to be correct for me, the count of found pages for Delorme is too high for almost all states in my case. I never was in Arkansas, but it says "4 of 46" in the overview. When tapping on the state, it first says "4 of 46 - 42 missing", but in the list of pages all show a "0", and also the map is all red.
For states where I have some pages found, the number can also be too high, e.g. FL should be 9, but it reads 25.
This is in the German localization, so maybe some string matching issue? Only two states show "0", incl. Minnesota-2010, while Minnesota shows 14. Some states show as completely found, although I never was there.
Let me know if you need the "my finds.gpx"

**To Reproduce**

**Expected behavior**
Number of pages with non-zero founds is reported.

**Screenshots**

**Cachly version**
 - 8.0.7 (5)

**iOS device (please complete the following information):**
 - Device: iPhone13
 - OS: iOS 18.1

**Additional context**

**Comment by cachly** [comment]
There have been many changes to Delorme during the 8.0 beta period. Can you please clear all Delorme and reimport to see if there is still the issue?

**Comment by ThomGr** [comment]
yep, fixed
