### ISSUE TITLE
Searching for caches 

### ISSUE THREAD

**Issue by LesRogeries** [cachly/issues-tracker#5100]
In Pro if in live I press the X icon Cachley has no search icon I have to move the map before it will search & will not find all caches. Often I have to reset the search parimiters 

![cachly](https://github.com/user-attachments/assets/7c180160-fb3e-4ceb-aa4d-9af3e7f5649a)

**Expected behavior**
A seach button

**Screenshots**
![image](https://github.com/user-attachments/assets/2f6d8a04-35cb-4802-a0b7-1d4dd969454b)

**Cachly version**
 - Version: [e.g. 8.0.6 (1)]

**iOS device (please complete the following information):**
 - Device: iphone13
 - OS: [e.g. iOS 17.6.1

**Additional context**

**Comment by cachly** [comment]
@LesRogeries It looks like you have turned on auto refresh, where Cachly searches as you move the map instead of having the reset button. Long press on the red "Auto" button to change that back to what you are wanting.

**Comment by LesRogeries** [comment]
Thanks 

Jacky

**Comment by LesRogeries** [comment]
Hi Nicholas

Next question without the X how does one clear local searches as I’ve got caches that remain on the map. Which is better to use Auto or not. As sometimes Auto doesn’t find all the caches in the area I sometimes have to use the geocaching app to check(sorry)

 

Jacky
