### ISSUE TITLE
Ability to declare default coordinate format when copying

### ISSUE THREAD

**Issue by LostLooker** [cachly/issues-tracker#5104]
When you added the 3 options for coordinate types in the Copy Coordinates option, it threw me for a loop and I’m still not used to it.  When I go to paste the coordinates elsewhere, I realize they are not in my buffer yet because I didn’t choose the coordinate style when I copied them.

I really only ever use UTM coordinates, so could you allow us to declare which is our default coordinate style so that it does go into the paste buffer right away when we choose Copy Coordinates?

I don’t know how many other people would appreciate this setting because frankly, I’m the only one I’ve heard complaing about it.
![IMG_8537](https://github.com/user-attachments/assets/f4339edf-bb7a-4d68-a494-7618e68b3091)

**Comment by PlasmaWave** [comment]
I agree this is a useful feature and rarely use anything but the "default" geocaching format at the top of the list

**Comment by cachly** [comment]
How often are you copying coordinates?

**Comment by PlasmaWave** [comment]
I copy co-ords very regularly ... probably every day and often several times a day. Usually as standard geocaching format but occasionally DD format. Would really be useful not to need to choose the format every time.

I use the copy co-ords function mainly for picking an access/parking location, both for caching and non-caching navigation.

Would also love to remove the leading zero in Northings ... thought we discussed that in the Beta Group

**Comment by cachly** [comment]
Fixed in 8.0.9.
