### ISSUE TITLE
Online Drafts: Incorrect draft count after the app got restored

### ISSUE THREAD

**Issue by JanRei** [cachly/issues-tracker#5113]
**Describe the bug**
Cachly incorrectly displays "0 Drafts" after it has been restored. The issue is more likely to occur with a high number of drafts. I encountered the issue when I had about 30 drafts.

**To Reproduce**
1. Create some drafts.
2. Go to "More" -> "Online Drafts". See the correct draft count at the top of the screen.
2. Let the app being killed, for example by opening other apps.
3. Open Cachly again.
4. See that it now says "0 Drafts" above the list of drafts.

**Expected behavior**
The correct number of drafts should be displayed. Or, if this is not possible, the number should be better hidden to avoid confusing the user.

**Screenshots**
![onlinedrafts_wrong_count](https://github.com/user-attachments/assets/6af056bd-c3ec-4735-9d2f-25956bea3ef4)

**Cachly version**
 - Version: 8.0.8 (1)

**iOS device:**
 - Device: iPhone 12
 - OS: iOS 18.2

**Comment by cachly** [comment]
When the state is restored Cachly will call the API again and load the drafts again. I cannot replicate this.

**Comment by cachly** [comment]
Never mind, I replicated it. Fixed for 8.0.9.
